### PR TITLE
Update plugin to support multi-project builds

### PR DESCRIPTION
**Pull request by dabd**
### What
* Add support for configuring the package name where the snapshot config will be generated.

### Why
* To avoid name clashes in multi-project builds.

### CODE REVIEW

**Comment by zainab-ali** [comment]
Thanks so much for contributing @dabd !

We're double checking the escaping of the package name, but are otherwise happy to accept this.

**Comment by zainab-ali** [comment]
Hi @dabd,

Could you give some more details on your multi-module setup? It would be great if you could provide a snippet of your `build.sbt`.

For context, I'm working on a scripted test for multi-module support [here](https://github.com/siriusxm/snapshot4s/compare/main...zainab-ali:multi-module-setup).

Snapshot4s works correctly for the `core`, `utils` and `framework` modules in the scripted test.

To illustrate a bug, there's a `extra` module with the same `test->test` dependency, but which omits the `Snapshot4sPlugin`. This bug is a bit complex. Since the `snapshot4s.generated.snapshotConfig` for `extra` isn't generated, there is only a `snapshot4s.generated.snapshotConfig` corresponding to `core` on the classpath. The `core` module gets updated with the `extra` snapshot values. This only happens for file snapshots, as we have validation for inline snapshots that prevents this.

We might be able to address this bug through better validation for file snapshots.

Going back to your suggestion of custom package names, [sbt-buildinfo](https://github.com/sbt/sbt-buildinfo?tab=readme-ov-file#buildinfooptionconstantvalue)'s approach of having a configurable package name and package-private object might be event better.  It wouldn't be possible to compile a test with the wrong `SnapshotConfig`.

**Comment by dabd** [comment]
> Hi @dabd,
> 
> Could you give some more details on your multi-module setup? It would be great if you could provide a snippet of your `build.sbt`.
> 
> For context, I'm working on a scripted test for multi-module support [here](https://github.com/siriusxm/snapshot4s/compare/main...zainab-ali:multi-module-setup).
> 
> Snapshot4s works correctly for the `core`, `utils` and `framework` modules in the scripted test.
> 
> To illustrate a bug, there's a `extra` module with the same `test->test` dependency, but which omits the `Snapshot4sPlugin`. This bug is a bit complex. Since the `snapshot4s.generated.snapshotConfig` for `extra` isn't generated, there is only a `snapshot4s.generated.snapshotConfig` corresponding to `core` on the classpath. The `core` module gets updated with the `extra` snapshot values. This only happens for file snapshots, as we have validation for inline snapshots that prevents this.
> 
> We might be able to address this bug through better validation for file snapshots.
> 
> Going back to your suggestion of custom package names, [sbt-buildinfo](https://github.com/sbt/sbt-buildinfo?tab=readme-ov-file#buildinfooptionconstantvalue)'s approach of having a configurable package name and package-private object might be event better. It wouldn't be possible to compile a test with the wrong `SnapshotConfig`.

I tried to use the library at work, so unfortunately I can't share the build.sbt file :)   It looks like following the same approach as in `sbt-build-info`, with configurable package names and package-private object would fix the bug you have found.

**Comment by zainab-ali** [comment]
Thanks for taking a look @dabd . If that's the bug you're experiencing, you should be able to resolve it by adding the `Snapshot4sPlugin` to each module in your project that contains snapshot tests.

If that doesn't work, it would be very helpful if you could describe exactly what's going wrong. For instance:
 - Whether you're running `assertInlineSnapshot` or `assertFileSnapshot`.
 - Whether snapshot4s is updating your files or not.
 - What the contents of the `Snapshot4sBuildInfo.scala` in each module is (feel free to obfuscate paths here).

It would be good to understand the root cause of the issue, regardless of whether we move to a package-private object.

**Comment by dabd** [comment]
> Thanks for taking a look @dabd . If that's the bug you're experiencing, you should be able to resolve it by adding the `Snapshot4sPlugin` to each module in your project that contains snapshot tests.
> 
> If that doesn't work, it would be very helpful if you could describe exactly what's going wrong. For instance:
> 
> * Whether you're running `assertInlineSnapshot` or `assertFileSnapshot`.
> * Whether snapshot4s is updating your files or not.
> * What the contents of the `Snapshot4sBuildInfo.scala` in each module is (feel free to obfuscate paths here).
> 
> It would be good to understand the root cause of the issue, regardless of whether we move to a package-private object.

To be clear, I didn't find a bug, this PR was intended to provide a solution for name clashes in multi-module projects.
As you said above, the `sbt-buildinfo` approach should avoid this issue and prevent the classpath bug you discovered, so feel free to close this PR if you decide to go with that.

**Comment by majk-p** [comment]
I'd like to wrap up the discussion and set everyone on the same page. To start with, the main motivation for the change is "to avoid name clashes in multi-project builds". I totally see where you're coming from with adding an sbt config parameter. That might be the solution, but I'm not sure if we even have the issue in the first place. 

In https://github.com/siriusxm/snapshot4s/compare/main...zainab-ali:multi-module-setup @zainab-ali has demonstrated a working multi-module setup so, if I understand everything correctly, I think there's nothing to address in the first place. 

I really appreciate the controbution! The discussion has helped us better understand the corner cases of user setup. However, I'm reluctant to implement the change that requires users to switch from a generic `import snapshot4s.generated.snapshotConfig' to a specific `import snapshot4s.my_project.generated.snapshotConfig' plus adding an extra configuration flag. This makes the usage side of things more complicated and requires additional maintenance. It's easy to expose an additional sbt setting, but hard to migrate/deprecate one

That said, if we are able to handle the case of multi-project builds with detailed documentation, I'd prefer that over extending plugin's interface.

**Pull request closed without merging**
